version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y apache2
  build:
    commands:
      - echo "Build phase"
  post_build:
    commands:
      - echo "Post-build phase"
